### ISSUE TITLE
Docking issue

### ISSUE THREAD

**Issue by Johnson7L** [MatthijsHak/MetalDock#2] opened 2023-10-17 04:08 UTC
Dear developer,

I attempted to execute the example from the "MetalDock" paper, which involves the interaction between (A)-19 and 3CLpro. However, I encountered errors during the docking process shown as followed.

GPF> nbp_r_eps 0.25 23.2135   12 6  NA TZ

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.10  3.8453   12 6  OA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.25  7.5914   12 6  SA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 1.00  0.0000   12 6  HD Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.00  0.0060   12 6  NA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.00  0.2966   12 6  N  Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.20  6.7380   12 10 NA Re

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.25  0.6450   12 10 OA Re

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.30  3.3090   12 10 SA Re

Overriding non-bonded interaction energies for

Overriding non-bonded interaction energies for docking calculation;
Segmentation fault (core dumped)
/Documents/MetalDock/src/external/AutoDock/autodock4: creating docking log file ligand_clean_6y2f.dlg
/Documents/MetalDock/src/external/AutoDock/autodock4: ERROR:  Unknown ligand atom type "2.00.2966"; add parameters for it to the parameter library first!
/Documents/MetalDock/src/external/AutoDock/autodock4:         Edit the parameter library file "metal_dock.dat" and try again.
/Documents/MetalDock/src/external/AutoDock/autodock4: FATAL ERROR: /Documents/MetalDock/src/external/AutoDock/autodock4:         Edit the parameter library file "metal_dock.dat" and try again.

/Documents/MetalDock/src/external/AutoDock/autodock4: Unsuccessful Completion.

**I sincerely appreciate your assistance in advance.**

Regards,
Z. LIN

**Comment by MatthijsHak** [comment] 2023-10-17 04:43
Dear Lin,

Could you please provide me with the all the files, input from you and output generated by MetalDock. From this output alone I can not deduce what went wrong. Thank you in advance.

Regards,

Matthijs

**Comment by Johnson7L** [comment] 2023-10-17 05:09
Dear Matthijs,

I sincerely appreciate your response.

The files will be attached to this comment.

Regards,
Z. [LIN[](url)]([url](url))
[test.zip](https://github.com/MatthijsHak/MetalDock/files/12924417/test.zip)

**Comment by MatthijsHak** [comment] 2023-10-17 08:11
Dear Z. Lin,

You used an older setting the standard = True. Could you please help me where I used this setting as an example, so that I can delete it. Currently, your settings are running on my computer with the .ini file attached to this comment. 

Be aware, you are using the RMSD parameter, but as you do not have a X-ray structure as reference for the Rhenium complex, it uses the geometry optimised coordinates of the metal complex to determine the RMSD, which is in a different local frame than the PDB file.

[orca_input_ini.txt](https://github.com/MatthijsHak/MetalDock/files/12926092/orca_input_ini.txt)

If you encounter any future problems, please do not hesitate to write an issue.

Regards,

Matthijs

**Comment by MatthijsHak** [comment] 2023-10-17 08:25
Ah okay great to know. I changed that so it should run smoothly now. Let me know if the issue is fixed, then we can close it.

**Comment by MatthijsHak** [comment] 2023-10-17 08:27
Sorry I forgot to say, but you should git clone once again, as the source code has been changed.

**Comment by Johnson7L** [comment] 2023-10-18 08:32
Dear Matthijs,

After using the new source code, the docking issue still remains.

GPF> nbp_r_eps 0.25 23.2135   12 6  NA TZ

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.10  3.8453   12 6  OA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.25  7.5914   12 6  SA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 1.00  0.0000   12 6  HD Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.00  0.0060   12 6  NA Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.00  0.2966   12 6  N  Zn

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.20  6.7380   12 10 NA Re

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.25  0.6450   12 10 OA Re

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 2.30  3.3090   12 10 SA Re

Overriding non-bonded interaction energies for docking calculation;
GPF> nbp_r_eps 1.00  4.5020   12 6  HD Re

Overriding non-bonded interaction energies for docking calculation;
Segmentation fault (core dumped)
/Documents/MetalDock/src/external/AutoDock/autodock4: creating docking log file ligand_clean_6y2f.dlg
/Documents/MetalDock/src/external/AutoDock/autodock4: ERROR:  Unknown ligand atom type "2.00.2966"; add parameters for it to the parameter library first!
/Documents/MetalDock/src/external/AutoDock/autodock4:         Edit the parameter library file "metal_dock.dat" and try again.
/Documents/MetalDock/src/external/AutoDock/autodock4: FATAL ERROR: /Documents/MetalDock/src/external/AutoDock/autodock4:         Edit the parameter library file "metal_dock.dat" and try again.

/Documents/MetalDock/src/external/AutoDock/autodock4: Unsuccessful Completion.

**Additionally**, there are two typos in the source code.
In line 541 of /MetalDock/src/metal_dock/prepare_dock.py, the "clean_{par.name_protein}.pdb" needs to be edited as " clean_{name_protein}.pdb".
In line 120 of /MetalDock/src/metal_dock/docking.py", the "d.docking_func(par, par.parameter_set, par.name_ligand, par.name_protein, dock, box_size, energy)" needs to be edited as "d.docking_func(par, dock, box_size, energy)".

Regards,
Z.LIN

**Comment by Johnson7L** [comment] 2023-10-18 10:28
Dear Matthijs,

I ran again after downloading the new source code and the issue still remained (without path problems).

I attached the all files via this comment, which might be helpful to analyse the cause.

[test.zip](https://github.com/MatthijsHak/MetalDock/files/13009897/test.zip)

Regards,
Z.LIN

**Comment by MatthijsHak** [comment] 2023-10-18 10:48
For me the code works, but I am able to reproduce your error by commenting out line 546 in prepare_dock.py. As I do not have your complete output, I can not exactly know why this particular line of code is not properly executed. 

Could you verify that the MetalDock/src/external/AutoDockTools dir is present. 
Could you also verify that the ROOT_DIR in environment_variables.py is set correctly. You can do this by adding print(ROOT_DIR) on line 6 in environment_variables.py. You should see the path to MetalDock/src 
Could you verify that you have python2.7 in your conda environment.

Regards,

Matthijs

**Comment by Johnson7L** [comment] 2023-10-19 02:11
Dear Matthijs,

Yeah. You are right. I create a new environment for python2.7 and set a path to it. The docking can run smoothly now.

I am sincerely grateful for your unwavering assiantance and patience!

Regards,
Z.LIN

**Comment by MatthijsHak** [comment] 2023-10-19 09:29
Dear Zexiong,

Great that it works. I now removed the dependency on python2, so that in the future this error hopefully will not occur anymore. I will close this issue now.

Regards,

Matthijs

**Closed by MatthijsHak** 2023-10-19 09:29 UTC
